"""empty message

Revision ID: 04b24a065828
Revises: e03c8fa7461d
Create Date: 2024-02-14 22:27:35.933898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04b24a065828'
down_revision = 'e03c8fa7461d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activities')),
    sa.UniqueConstraint('activity', name=op.f('uq_activities_activity')),
    sa.UniqueConstraint('type', name=op.f('uq_activities_type'))
    )
    op.create_table('dogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dogs')),
    sa.UniqueConstraint('name', name=op.f('uq_dogs_name'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dogs')
    op.drop_table('activities')
    # ### end Alembic commands ###
