"""empty message

Revision ID: 5b08caf55dd2
Revises: 04b24a065828
Create Date: 2024-02-14 23:08:50.992847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b08caf55dd2'
down_revision = '04b24a065828'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_constraint('uq_activities_type', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_activities_type', ['type'])

    # ### end Alembic commands ###
