"""empty message

Revision ID: ff68b7f7971f
Revises: e5c9579f5b55
Create Date: 2024-02-15 20:51:01.526614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff68b7f7971f'
down_revision = 'e5c9579f5b55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routines', schema=None) as batch_op:
        batch_op.drop_constraint('uq_routines_dog_id', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routines', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_routines_dog_id', ['dog_id'])

    # ### end Alembic commands ###
